### ISSUE TITLE
Мои предложения

### ISSUE THREAD

**Issue by KOT040188** [loast/krudio#12]
Пишу сразу всё, дабы не забыть.
1. Вместо значка в трее пустое место. Добавьте возможность вручную менять значки в трее для состояний остановки/паузы/воспроизведения.
2. Добавьте в меню ПКМ по значку в трее список радиостанций для переключения, как в radiotray и kradio4 и кнопку поиска композиции в интернете.
3. Добавьте к значку в трее подсказку с названием радиостанции и информацией о композиции.
4. Добавьте возможность ЛКМ по значку в трее и кнопку в окно полностью останавливать воспроизведение без буферизации. Мне буферизация как при паузе не нужна, к тому же иногда она заканчивается и композиция жёстко перескакивает на другую. Это раздражает.
5. Добавьте возможность СКМ по значку в трее открывать поиск композиции в интернете.
6. Добавьте возможность управления через MPRIS.
7. Добавьте категории для станций.
8. Добавьте подсказки к кнопкам в окне.
9. При запуске значёк в трее по умолчанию спрятан, в настройках трея стоит автоматически показывать значёк. Это нормально? Я не заметил и запустил пять копий. Я думаю стоит запретить запуск больше одной копии.
Пока всё. Очень надеюсь на реализацию вышеизложенного. Спасибо.

**Comment by alexyalinc** [comment]
> Пока всё. Очень надеюсь на реализацию вышеизложенного. Спасибо.

А я то как надеюсь :3 
Вручную менять значки не дам. Значки будут меняться в зависимости от используемой темы значков (Если в теме нет значков, то используются дефолтные). 
Второе. Подумаю над этим. 
Третье. Сделаю. 
Четвертое. Сделаю, чтобы был стоп,  а не пауза. Пойдет?
Пятое. Добавлю.
Шестое. Пдумаю.
Седьмое. Сделаю.
Восьмое. Сделаю.
Девятое. Над копиями разберусь. А на счет трея не понял о чем реч.
И прежде чем писать на других источниках, что автор не такой, какой хотелось бы. Подумай, что он сделал приложение, которое работает и которым ты пользуешься. Да, я не всегда выхожу на связь, у меня есть и другие дела. Но я постараюсь сделать все, что мне покажется нужным в этом приложении.

**Comment by KOT040188** [comment]
1. Вы меня очень сильно огорчили. Поймите, что обычно тема значков хорошо подходит для панели задач, для меню запуска. А для трея ну никак не подходит. Для него больше подходит упрощённый схематичный вариант.  Эстетика блин. Я хоть и не дизайнер, но понимаю это. Если дефолтные будут неплохие, то пусть будут, но мне например нравятся такие https://dl.dropboxusercontent.com/u/85152410/radiotray_connecting.svg и https://dl.dropboxusercontent.com/u/85152410/radiotray_on.svg. Они как раз есть в наборе numix-circle.  но кроме как ручной заменой, другого способа я не нашёл как изменить их для kradio. Но это костыль.
2. А что тут думать? Сейчас в меню значка в трее нет никакого смысла. Почему бы его не добавить?
3. Ну мне-то пойдёт. Не знаю как другим. Может сделать выбор в настройках?
4. Я хочу объяснить для чего мне это нужно. Я использую kdeconnect. Надеюсь слышали о нём? Если не слышали, погуглите, весьма крутая штука. Так вот когда мне кто-нибудь звонит на андроид, kdeconnect вырубает все играющи приложения доступные через MPRIS (в том числе и kradio, radioitray и amarok). А после разговора снова запускает. Очень удобно.
5. Ну что тут непонятного. Вы же kde используете. Или уже нет? По умолчанию значок вашего радио спрятан в трее в выпадающем меню. Он скрыт и не показывается на панели. А настройка для него по умолчанию стоит показывать автоматически, это стандартная настройка для всех новых значков. Но при этой стандартной настройке kradio и radioitray показывают свой значок на панели. Вот я и спрашиваю нормально ли это поведение. Мне пришлось выставлять режим для значка "показывать всегда". Мелочь, а не приятно…
   >
   И прежде чем писать на других источниках, что автор не такой, какой хотелось бы. Подумай, что он сделал приложение, которое работает и которым ты пользуешься.
   Я подумаю. Но я считаю, что простой пользователь как я не должен думать как же скомпилировать ваше приложение. Разработчик doublecmd например добавил его в официальные источники приложений ubuntu. Я пока приложением не пользуюсь. Хотя оно и запущено. Причины выше в списке. Прошу вас подумать, для кого вы делаете приложение. Если для себя, то не стоило меня так обнадёживать, писать заметку на сайте… А если всё-таки для пользователей, то вот он я, вот мои предложения. Вы хозяин своего проекта. Можете сделать его для себя, а можете сделать уникальное предложение (для linux по крайней мере, два вышеупомянутых почти сдохли), которым будут с удовольствием пользоваться другие люди и вспоминать вас добрым словом. Простите, если что не так, если был груб. На самом деле я нежный и пушистый кот. Просто эмоциональный, ибо не робот. Нисколечки не хотел вас обидеть. Добра вам и здоровья.

**Comment by varlesh** [comment]
@KOT040188 
Все значки, в том числе и для трея цепляются из темы (если таковые имеются), как пример  Papirus. Там два статуса всего лишь играет/не играет.
С MPRIS согласен, нужная вещь )
Не будьте столь настойчивым и чуточку добрей. Автор отписал уже что в работе и попытается реализовать то, что возможно.

**Comment by KOT040188** [comment]
В нынешнее время без настойчивости, а иногда и без наглости трудно жить… Было бы здорово если бы я был программистом… Но увы, не сложилось, не моё это. А под linux подобных проектов как кот наплакал…

**Comment by alexyalinc** [comment]
@KOT040188 Ты еще начни тут филосовствовать. 

Принято в разработку

**Comment by KOT040188** [comment]
Извините, не буду больше…

**Comment by KOT040188** [comment]
Я вот что откопал по ссылке https://techbase.kde.org/Development/Tutorials/Plasma5/ThemeDetails#Current_Theme_Elements: 
`Theming these icons requires firstly that an application has been coded to use setIconByName, and secondly that you call your svg object by the same name (use ctrl+shift+o in Inkscape).`
Можно менять значки в трее с помощью темы плазмы. Я как раз пытаюсь отредактировать тему под себя. Только надо чтобы приложение использовало setIconByName. Что вы об этом думаете?

**Comment by alexyalinc** [comment]
@KOT040188 Я думаю, что это там есть, посмотрите, какие иконки используются по дефолту. Эти иконки заменяются, если в вашей используемой теме будут находится иконки с такими же названиями.

**Comment by KOT040188** [comment]
Я пробовал проделывать это для kradio - потерпел фиаско. Добавлял в тему плазмы значок с именем kradiuo и просто radio. Никакого толка…
