### ISSUE TITLE
Баги при отображении стилей Oxygen и Breeze

### ISSUE THREAD

**Issue by varlesh** [loast/krudio#6]
**Oxygen**
При первом запуске видно что кнопка play перекрывает pause
![screenshot_20160423_003855](https://cloud.githubusercontent.com/assets/8083855/14755587/13a9dfd6-08ec-11e6-896d-6d95e769587d.png)

Во вкладке добавления станций нижние кнопки за границей области окна
![screenshot_20160423_003805](https://cloud.githubusercontent.com/assets/8083855/14755643/75d842b0-08ec-11e6-8236-acc16eaf3ff6.png)

Во вкладке настройки трея над переключателями какая-то полоса
![screenshot_20160423_003947](https://cloud.githubusercontent.com/assets/8083855/14755674/accfcebe-08ec-11e6-8644-89c353161040.png)

**Breeze**
Так же во вкладке добавления станций нижние кнопки за границей области окна
![screenshot_20160423_004725](https://cloud.githubusercontent.com/assets/8083855/14755746/126f5172-08ed-11e6-9af1-79bd9ceb05d8.png)

Во вкладке настройки трея переключатели в какой-то рамке
![screenshot_20160423_004849](https://cloud.githubusercontent.com/assets/8083855/14755770/40530d86-08ed-11e6-8ce5-e3d86b0e757c.png)

**Comment by alexyalinc** [comment]
На счет кнопок понятно, исправлю, а там где радиокнопки это groupbox он обьединяет эти кнопки, чтобы можно было переключаться между ними. Но можно сделать и без него. В следующем обновлении исправлю!

**Comment by varlesh** [comment]
Спасибо Саш, все отлично 7e77dad212db5d1165635883daa6933bea5dec3b
